name: C/C++ CI

on: [push]

jobs:
  job:
    name: ${{matrix.config.name}} - ${{matrix.build_type}}
    runs-on: ${{matrix.config.os}}
    strategy:
      fail-fast: false
      matrix:
        build_type: ['Debug', 'Release']
        config:
          - {
            name: 'Windows Latest MSVC',
            os: windows-latest
          }
          - {
            name: 'Ubuntu Latest GCC',
            os: ubuntu-latest
          }
          - {
            name: 'MacOS Latest Clang',
            os: macos-latest
          }
    steps:
      - uses: actions/checkout@v2
      - name: Configure
        shell: bash
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=${{matrix.build_type}}
      - name: Build GCC/Clang
        if: startsWith(matrix.config.os, 'windows') == false
        shell: bash
        run: |
          cd build
          make -j4
      - name: Build MSVC
        if: startsWith(matrix.config.os, 'windows')
        run: |
          cd build
          make -j4