name: Linux Build

on: [push]

jobs:
  job:
    name: ${{matrix.config.name}} - ${{matrix.build_type}}
    runs-on: ${{matrix.config.os}}
    strategy:
      fail-fast: false
      matrix:
        build_type: ['Debug', 'Release']
        config:
          - {
            name: 'Ubuntu Latest GCC',
            os: ubuntu-latest
          }
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - name: Install dependencies
        shell: bash
        run: |
          sudo apt-get install -y libxrandr2 libxrandr-dev
          sudo apt-get install -y libxinerama-dev libxcursor-dev libxi-dev
          sudo apt-get install -y libgl1-mesa-dev
      - name: Configure
        shell: bash
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=${{matrix.build_type}}
      - name: Build
        shell: bash
        run: |
          cd build
          cmake --build . --target example_test --config ${{matrix.build_type}} -j6
